// Generated by scripts/process-photos.mjs. Edit its curated selections, then re-run npm run photos.
export type BoatPhoto = {
  id: string;
  src: string;
  srcSet: string;
  width: number;
  height: number;
  alt: string;
  caption: string;
  category: string;
  originalFilename: string;
};

export const photos: BoatPhoto[] = [
  {
    id: "port-profile",
    src: "/images/boat/2018-jeanneau-nc-895-ez-livin-port-profile-1600.webp",
    srcSet:
      "/images/boat/2018-jeanneau-nc-895-ez-livin-port-profile-480.webp 480w, /images/boat/2018-jeanneau-nc-895-ez-livin-port-profile-960.webp 960w, /images/boat/2018-jeanneau-nc-895-ez-livin-port-profile-1600.webp 1600w, /images/boat/2018-jeanneau-nc-895-ez-livin-port-profile-2400.webp 2050w",
    width: 1600,
    height: 1199,
    alt: "Port exterior profile of the 2018 Jeanneau NC 895 EZ Livin at anchor",
    caption: "EZ Livin at anchor",
    category: "Exterior",
    originalFilename: "DA18D8EE20EE67A1783F0C55B0D60CDF.jpg",
  },
  {
    id: "starboard-profile",
    src: "/images/boat/2018-jeanneau-nc-895-ez-livin-starboard-profile-1600.webp",
    srcSet:
      "/images/boat/2018-jeanneau-nc-895-ez-livin-starboard-profile-480.webp 480w, /images/boat/2018-jeanneau-nc-895-ez-livin-starboard-profile-960.webp 960w, /images/boat/2018-jeanneau-nc-895-ez-livin-starboard-profile-1600.webp 1600w, /images/boat/2018-jeanneau-nc-895-ez-livin-starboard-profile-2400.webp 2048w",
    width: 1600,
    height: 1200,
    alt: "Starboard exterior profile of EZ Livin beside a sandy shoreline",
    caption: "Starboard profile",
    category: "Exterior",
    originalFilename: "0AF73F6752FC95BB51574A0FF9F09DD3.jpg",
  },
  {
    id: "bow-overhead",
    src: "/images/boat/2018-jeanneau-nc-895-ez-livin-bow-overhead-1600.webp",
    srcSet:
      "/images/boat/2018-jeanneau-nc-895-ez-livin-bow-overhead-480.webp 480w, /images/boat/2018-jeanneau-nc-895-ez-livin-bow-overhead-960.webp 960w, /images/boat/2018-jeanneau-nc-895-ez-livin-bow-overhead-1600.webp 1600w, /images/boat/2018-jeanneau-nc-895-ez-livin-bow-overhead-2400.webp 2048w",
    width: 1600,
    height: 1200,
    alt: "Elevated view of EZ Livin showing the bow, deck rails and pilothouse roof",
    caption: "Bow and pilothouse roof",
    category: "Exterior",
    originalFilename: "53748D47C7656DC2A085A09F38B9BA0A.jpg",
  },
  {
    id: "bow-view",
    src: "/images/boat/2018-jeanneau-nc-895-ez-livin-bow-view-1600.webp",
    srcSet:
      "/images/boat/2018-jeanneau-nc-895-ez-livin-bow-view-480.webp 480w, /images/boat/2018-jeanneau-nc-895-ez-livin-bow-view-960.webp 960w, /images/boat/2018-jeanneau-nc-895-ez-livin-bow-view-1600.webp 1600w, /images/boat/2018-jeanneau-nc-895-ez-livin-bow-view-2400.webp 2048w",
    width: 1600,
    height: 1200,
    alt: "View toward the bow of EZ Livin showing the forward windshield and deck rails",
    caption: "Forward exterior view",
    category: "Exterior",
    originalFilename: "BBE74D8D7AAD897B0603F49BBE35B9DC.jpg",
  },
  {
    id: "stern-twin-yamaha",
    src: "/images/boat/2018-jeanneau-nc-895-ez-livin-stern-twin-yamaha-1600.webp",
    srcSet:
      "/images/boat/2018-jeanneau-nc-895-ez-livin-stern-twin-yamaha-480.webp 480w, /images/boat/2018-jeanneau-nc-895-ez-livin-stern-twin-yamaha-960.webp 960w, /images/boat/2018-jeanneau-nc-895-ez-livin-stern-twin-yamaha-1600.webp 1600w, /images/boat/2018-jeanneau-nc-895-ez-livin-stern-twin-yamaha-2400.webp 2050w",
    width: 1600,
    height: 1199,
    alt: "Stern view of EZ Livin showing twin Yamaha 200 outboards, swim platforms and shaded cockpit",
    caption: "Twin Yamaha 200s and aft cockpit",
    category: "Exterior",
    originalFilename: "8036D2DC306EF5C5C9534C3FD49518B3.jpg",
  },
  {
    id: "shoreline-aerial",
    src: "/images/boat/2018-jeanneau-nc-895-ez-livin-shoreline-aerial-1600.webp",
    srcSet:
      "/images/boat/2018-jeanneau-nc-895-ez-livin-shoreline-aerial-480.webp 480w, /images/boat/2018-jeanneau-nc-895-ez-livin-shoreline-aerial-960.webp 960w, /images/boat/2018-jeanneau-nc-895-ez-livin-shoreline-aerial-1600.webp 1600w, /images/boat/2018-jeanneau-nc-895-ez-livin-shoreline-aerial-2400.webp 2048w",
    width: 1600,
    height: 1200,
    alt: "Aerial view of EZ Livin anchored beside a sandbar",
    caption: "A day on the water",
    category: "Exterior",
    originalFilename: "CFF756CB0EDF871B93D0D401DD71B550.jpg",
  },
  {
    id: "salon-galley",
    src: "/images/boat/2018-jeanneau-nc-895-ez-livin-salon-galley-1600.webp",
    srcSet:
      "/images/boat/2018-jeanneau-nc-895-ez-livin-salon-galley-480.webp 480w, /images/boat/2018-jeanneau-nc-895-ez-livin-salon-galley-960.webp 960w, /images/boat/2018-jeanneau-nc-895-ez-livin-salon-galley-1600.webp 1600w, /images/boat/2018-jeanneau-nc-895-ez-livin-salon-galley-2400.webp 2048w",
    width: 1600,
    height: 1200,
    alt: "Bright pilothouse of EZ Livin with salon seating, galley and panoramic windows",
    caption: "A bright, practical pilothouse",
    category: "Interior",
    originalFilename: "IMG_8953.jpg",
  },
  {
    id: "salon-dinette",
    src: "/images/boat/2018-jeanneau-nc-895-ez-livin-salon-dinette-1600.webp",
    srcSet:
      "/images/boat/2018-jeanneau-nc-895-ez-livin-salon-dinette-480.webp 480w, /images/boat/2018-jeanneau-nc-895-ez-livin-salon-dinette-960.webp 960w, /images/boat/2018-jeanneau-nc-895-ez-livin-salon-dinette-1600.webp 1600w, /images/boat/2018-jeanneau-nc-895-ez-livin-salon-dinette-2400.webp 2048w",
    width: 1600,
    height: 1200,
    alt: "Salon dinette with wood table, bench seating and sliding aft glass door",
    caption: "Salon dinette",
    category: "Interior",
    originalFilename: "IMG_8941.jpg",
  },
  {
    id: "salon-aft-view",
    src: "/images/boat/2018-jeanneau-nc-895-ez-livin-salon-aft-view-1600.webp",
    srcSet:
      "/images/boat/2018-jeanneau-nc-895-ez-livin-salon-aft-view-480.webp 480w, /images/boat/2018-jeanneau-nc-895-ez-livin-salon-aft-view-960.webp 960w, /images/boat/2018-jeanneau-nc-895-ez-livin-salon-aft-view-1600.webp 1600w, /images/boat/2018-jeanneau-nc-895-ez-livin-salon-aft-view-2400.webp 2048w",
    width: 1600,
    height: 1200,
    alt: "View aft through the salon showing the dinette and sliding cockpit door",
    caption: "Salon and aft glass door",
    category: "Interior",
    originalFilename: "IMG_8964.jpg",
  },
  {
    id: "galley-sink-cooktop",
    src: "/images/boat/2018-jeanneau-nc-895-ez-livin-galley-sink-cooktop-1600.webp",
    srcSet:
      "/images/boat/2018-jeanneau-nc-895-ez-livin-galley-sink-cooktop-480.webp 480w, /images/boat/2018-jeanneau-nc-895-ez-livin-galley-sink-cooktop-960.webp 960w, /images/boat/2018-jeanneau-nc-895-ez-livin-galley-sink-cooktop-1600.webp 1600w, /images/boat/2018-jeanneau-nc-895-ez-livin-galley-sink-cooktop-2400.webp 2048w",
    width: 1600,
    height: 1200,
    alt: "Galley with stainless sink, two-burner cooktop and refrigerator below",
    caption: "Galley sink, cooktop and refrigerator",
    category: "Interior",
    originalFilename: "IMG_8947.jpg",
  },
  {
    id: "galley-microwave",
    src: "/images/boat/2018-jeanneau-nc-895-ez-livin-galley-microwave-1600.webp",
    srcSet:
      "/images/boat/2018-jeanneau-nc-895-ez-livin-galley-microwave-480.webp 480w, /images/boat/2018-jeanneau-nc-895-ez-livin-galley-microwave-960.webp 960w, /images/boat/2018-jeanneau-nc-895-ez-livin-galley-microwave-1600.webp 1600w, /images/boat/2018-jeanneau-nc-895-ez-livin-galley-microwave-2400.webp 2048w",
    width: 1600,
    height: 1200,
    alt: "Microwave installed below the wood galley counter aboard EZ Livin",
    caption: "Galley microwave",
    category: "Interior",
    originalFilename: "IMG_8988.jpg",
  },
  {
    id: "pilothouse-windshield-roof",
    src: "/images/boat/2018-jeanneau-nc-895-ez-livin-pilothouse-windshield-roof-1600.webp",
    srcSet:
      "/images/boat/2018-jeanneau-nc-895-ez-livin-pilothouse-windshield-roof-480.webp 480w, /images/boat/2018-jeanneau-nc-895-ez-livin-pilothouse-windshield-roof-960.webp 960w, /images/boat/2018-jeanneau-nc-895-ez-livin-pilothouse-windshield-roof-1600.webp 1600w, /images/boat/2018-jeanneau-nc-895-ez-livin-pilothouse-windshield-roof-2400.webp 2048w",
    width: 1600,
    height: 1200,
    alt: "Forward view from the pilothouse showing the windshield, helm and overhead opening hatches",
    caption: "Visibility and overhead light",
    category: "Interior",
    originalFilename: "IMG_8950.jpg",
  },
  {
    id: "helm-lowrance-hds9",
    src: "/images/boat/2018-jeanneau-nc-895-ez-livin-helm-lowrance-hds9-1600.webp",
    srcSet:
      "/images/boat/2018-jeanneau-nc-895-ez-livin-helm-lowrance-hds9-480.webp 480w, /images/boat/2018-jeanneau-nc-895-ez-livin-helm-lowrance-hds9-960.webp 960w, /images/boat/2018-jeanneau-nc-895-ez-livin-helm-lowrance-hds9-1600.webp 1536w",
    width: 1536,
    height: 2048,
    alt: "Helm with Lowrance HDS9 display, Yamaha instrument screen, VHF and twin digital controls",
    caption: "Lowrance navigation and Yamaha controls",
    category: "Helm & systems",
    originalFilename: "IMG_8962.jpg",
  },
  {
    id: "helm-seat-side-door",
    src: "/images/boat/2018-jeanneau-nc-895-ez-livin-helm-seat-side-door-1600.webp",
    srcSet:
      "/images/boat/2018-jeanneau-nc-895-ez-livin-helm-seat-side-door-480.webp 480w, /images/boat/2018-jeanneau-nc-895-ez-livin-helm-seat-side-door-960.webp 960w, /images/boat/2018-jeanneau-nc-895-ez-livin-helm-seat-side-door-1600.webp 1536w",
    width: 1536,
    height: 2048,
    alt: "Adjustable helm seat beside the starboard sliding pilothouse door",
    caption: "Helm seat and starboard side door",
    category: "Helm & systems",
    originalFilename: "IMG_8958.jpg",
  },
  {
    id: "climate-control",
    src: "/images/boat/2018-jeanneau-nc-895-ez-livin-climate-control-1600.webp",
    srcSet:
      "/images/boat/2018-jeanneau-nc-895-ez-livin-climate-control-480.webp 480w, /images/boat/2018-jeanneau-nc-895-ez-livin-climate-control-960.webp 960w, /images/boat/2018-jeanneau-nc-895-ez-livin-climate-control-1600.webp 1536w",
    width: 1536,
    height: 2048,
    alt: "Digital marine climate control panel mounted in the salon",
    caption: "Marine climate controls",
    category: "Helm & systems",
    originalFilename: "IMG_8987.jpg",
  },
  {
    id: "forward-cabin",
    src: "/images/boat/2018-jeanneau-nc-895-ez-livin-forward-cabin-1600.webp",
    srcSet:
      "/images/boat/2018-jeanneau-nc-895-ez-livin-forward-cabin-480.webp 480w, /images/boat/2018-jeanneau-nc-895-ez-livin-forward-cabin-960.webp 960w, /images/boat/2018-jeanneau-nc-895-ez-livin-forward-cabin-1600.webp 1600w, /images/boat/2018-jeanneau-nc-895-ez-livin-forward-cabin-2400.webp 2048w",
    width: 1600,
    height: 1200,
    alt: "Forward private cabin with double berth, hull windows and wood storage lockers",
    caption: "Forward private cabin",
    category: "Cabins & head",
    originalFilename: "IMG_8982.jpg",
  },
  {
    id: "forward-cabin-aft-view",
    src: "/images/boat/2018-jeanneau-nc-895-ez-livin-forward-cabin-aft-view-1600.webp",
    srcSet:
      "/images/boat/2018-jeanneau-nc-895-ez-livin-forward-cabin-aft-view-480.webp 480w, /images/boat/2018-jeanneau-nc-895-ez-livin-forward-cabin-aft-view-960.webp 960w, /images/boat/2018-jeanneau-nc-895-ez-livin-forward-cabin-aft-view-1600.webp 1600w, /images/boat/2018-jeanneau-nc-895-ez-livin-forward-cabin-aft-view-2400.webp 2048w",
    width: 1600,
    height: 1200,
    alt: "View aft from the forward berth toward the private cabin door and hanging locker",
    caption: "Forward cabin storage and access",
    category: "Cabins & head",
    originalFilename: "IMG_8977.jpg",
  },
  {
    id: "second-cabin",
    src: "/images/boat/2018-jeanneau-nc-895-ez-livin-second-cabin-1600.webp",
    srcSet:
      "/images/boat/2018-jeanneau-nc-895-ez-livin-second-cabin-480.webp 480w, /images/boat/2018-jeanneau-nc-895-ez-livin-second-cabin-960.webp 960w, /images/boat/2018-jeanneau-nc-895-ez-livin-second-cabin-1600.webp 1600w, /images/boat/2018-jeanneau-nc-895-ez-livin-second-cabin-2400.webp 2048w",
    width: 1600,
    height: 1200,
    alt: "Lower second cabin berth with reading lights, wood trim and cushions",
    caption: "Second private cabin",
    category: "Cabins & head",
    originalFilename: "IMG_8986.jpg",
  },
  {
    id: "second-cabin-entry",
    src: "/images/boat/2018-jeanneau-nc-895-ez-livin-second-cabin-entry-1600.webp",
    srcSet:
      "/images/boat/2018-jeanneau-nc-895-ez-livin-second-cabin-entry-480.webp 480w, /images/boat/2018-jeanneau-nc-895-ez-livin-second-cabin-entry-960.webp 960w, /images/boat/2018-jeanneau-nc-895-ez-livin-second-cabin-entry-1600.webp 1536w",
    width: 1536,
    height: 2048,
    alt: "Entrance to the second cabin showing the berth and hull window",
    caption: "Second cabin access",
    category: "Cabins & head",
    originalFilename: "IMG_8985.jpg",
  },
  {
    id: "enclosed-head",
    src: "/images/boat/2018-jeanneau-nc-895-ez-livin-enclosed-head-1600.webp",
    srcSet:
      "/images/boat/2018-jeanneau-nc-895-ez-livin-enclosed-head-480.webp 480w, /images/boat/2018-jeanneau-nc-895-ez-livin-enclosed-head-960.webp 960w, /images/boat/2018-jeanneau-nc-895-ez-livin-enclosed-head-1600.webp 1536w",
    width: 1536,
    height: 2048,
    alt: "Enclosed head with installed marine toilet, basin, wood vanity and opening port",
    caption: "Enclosed head",
    category: "Cabins & head",
    originalFilename: "IMG_8970.jpg",
  },
  {
    id: "head-shower",
    src: "/images/boat/2018-jeanneau-nc-895-ez-livin-head-shower-1600.webp",
    srcSet:
      "/images/boat/2018-jeanneau-nc-895-ez-livin-head-shower-480.webp 480w, /images/boat/2018-jeanneau-nc-895-ez-livin-head-shower-960.webp 960w, /images/boat/2018-jeanneau-nc-895-ez-livin-head-shower-1600.webp 1536w",
    width: 1536,
    height: 2048,
    alt: "Handheld shower fitting and basin inside the enclosed head",
    caption: "Shower in the enclosed head",
    category: "Cabins & head",
    originalFilename: "IMG_8967.jpg",
  },
  {
    id: "beach-cruising",
    src: "/images/boat/2018-jeanneau-nc-895-ez-livin-beach-cruising-1600.webp",
    srcSet:
      "/images/boat/2018-jeanneau-nc-895-ez-livin-beach-cruising-480.webp 480w, /images/boat/2018-jeanneau-nc-895-ez-livin-beach-cruising-960.webp 960w, /images/boat/2018-jeanneau-nc-895-ez-livin-beach-cruising-1600.webp 1600w, /images/boat/2018-jeanneau-nc-895-ez-livin-beach-cruising-2400.webp 2400w",
    width: 1600,
    height: 1200,
    alt: "EZ Livin anchored by a beach with other boats and people at the shoreline",
    caption: "Real days aboard EZ Livin",
    category: "Exterior",
    originalFilename: "Ocracoke.jpg",
  },
];

export const heroPhoto = photos.find((photo) => photo.id === "port-profile")!;

export const editorialPhotos = {
  owner: photos.find((photo) => photo.id === "beach-cruising")!,
  interior: photos.find((photo) => photo.id === "salon-galley")!,
  cabin: photos.find((photo) => photo.id === "forward-cabin")!,
  helm: photos.find((photo) => photo.id === "helm-lowrance-hds9")!,
  engines: photos.find((photo) => photo.id === "stern-twin-yamaha")!,
  cockpit: photos.find((photo) => photo.id === "stern-twin-yamaha")!,
};
